[package]
name = "flint-steel"
version.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
flint-core.workspace = true
dotenvy.workspace = true
rustc-hash = "2.1.1"
# rsjsonnet = "0.4.0" # for jsonnet support